name: Promotion System Automerge

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, review_requested]
    branches:
      - main

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.PAT }}
          merge-method: rebase
          required-labels: automerge
          dry-run: false
