name: Build and Release

on:
  pull_request:
    branches:
      - main
    types: ["closed"]

jobs:
  verify-labels:
    runs-on: ubuntu-latest
    outputs:
      contains-deploy-label: ${{ steps.verify-labels.outputs.contains-deploy-label }}
    steps:
      - name: Show context
        run: |
          echo "${{ toJson(github.event.pull_request) }}"

      - name: Verify labels
        id: verify-labels
        run: |
          labels=${{ toJson(github.event.pull_request.labels) }}
          for label in $(echo $labels | jq -r '.[].name'); do
            if [[ $label == "deploy-"* ]]; then
              echo "Label $label found"
              echo "contains-deploy-label=true" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "Labels not found"
              echo "contains-deploy-label=false" >> $GITHUB_OUTPUT
            fi
          done

  create-release:
    needs: verify-labels
    runs-on: ubuntu-latest
    if: needs.verify-labels.outputs.contains-deploy-label == 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 #v3.5.0
        with:
          token: ${{ secrets.PAT }}

      - name: Get next version
        id: get-next-version
        run: |
          git fetch --tags
          current_tag=$(git tag -l --sort=-v:refname | head -n 1)
          echo "next_version=$(echo $current_tag | awk -F. -v OFS=. '{$NF = $NF + 1;} 1')" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git config --local user.email "carlos.castro@jumo.world"
          git config --local user.name "Carlos Castro"
          git tag ${{ steps.get-next-version.outputs.next_version }}
          git push origin ${{ steps.get-next-version.outputs.next_version }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get-next-version.outputs.next_version }}
          generate_release_notes: true
          token: ${{ secrets.PAT }}
