name: On Deployment

on:
  deployment

jobs:
  create-pr:
    runs-on: ubuntu-latest
    name: Print Deployment Event Data
    steps:
      - run: |
          echo "${{ toJson(github.event.deployment) }}"
