name: Test PR closed

on:
  pull_request:
    branches:
      - main

jobs:
  doing-something:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 #v3.5.0

      - name: Do something
        run: |
          echo "Doing something"
