name: Trigger ArgoCD

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  verify-labels:
    runs-on: ubuntu-latest
    outputs:
      contains-deploy-label: ${{ steps.verify-labels.outputs.contains-deploy-label }}
    steps:
      - name: Verify labels
        id: verify-labels
        run: |
          labels=${{ toJson(github.event.pull_request.labels) }}
          for label in $(echo $labels | jq -r '.[].name'); do
            if [[ $label == "deploy-"* ]]; then
              echo "Label $label found"
              echo "contains-deploy-label=true" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "Labels not found"
              echo "contains-deploy-label=false" >> $GITHUB_OUTPUT
            fi
          done

  doing-something:
    needs: verify-labels
    runs-on: ubuntu-latest
    if: needs.verify-labels.outputs.contains-deploy-label == 'true'
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 #v3.5.0

      - name: Do something
        run: |
          echo "Create PR for kubernetes-manifests"
